<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <Company>Device Trust</Company>
    <Product>Device Trust .NET client SDK</Product>
    <Version>0.1.0</Version>
    <NoWarn>$(NoWarn);CA1848;CA1031</NoWarn>
  </PropertyGroup>

</Project>
